List all books on browsing to "/"
nilenso/athenaeum pull request #2
Opened 2020-12-17 17:15 UTC by qptr

2020-12-23 07:27 UTC, jysandy requested changes

2020-12-23 07:27 UTC, jysandy commented on test/clj/athenaeum/domain/book_test.clj
> +      (is (= "book1" (:books/title (first res))))
We should assert on the entire return value here.

2021-01-04 10:44 UTC, qptr commented
Looks like this with a dummy link
<img width="1791" alt="Screen Shot 2021-01-04 at 16 11 21" src="https://user-images.githubusercontent.com/71076330/103527151-ee553a80-4ea7-11eb-91ac-47c0c6cf1369.png">

and like this without
<img width="1791" alt="Screen Shot 2021-01-04 at 16 12 47" src="https://user-images.githubusercontent.com/71076330/103527101-dbdb0100-4ea7-11eb-8cf4-d3c8b0b66b83.png">

2021-01-05 07:24 UTC, jysandy requested changes
LGTM aside from the suggested changes.

2021-01-05 07:24 UTC, jysandy commented on src/cljs/athenaeum_web/routes.cljs
> +  [{:handler :home-page :page-name "Home"}])
Let's move this to be alongside the navbar.

2021-01-05 07:24 UTC, jysandy commented on test/clj/athenaeum/fixtures.clj
> +  (jdbc/execute! @db/datasource ["TRUNCATE TABLE books"])
We can use the `clear-tables` function from test-utils here.

2021-01-05 08:22 UTC, jysandy approved these changes

2021-01-05 08:22 UTC, merged